apiVersion: v1
kind: ServiceAccount
metadata:
  name: trigger
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: trigger
rules:
  - apiGroups:
      - triggers.tekton.dev
    resources:
      - eventlisteners
      - triggers
      - triggerbindings
      - triggertemplates
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - pipelineresources
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trigger
subjects:
  - kind: ServiceAccount
    name: trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: trigger

