apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: fedora:33
        command:
          - "/bin/bash"
        args:
          - "-c"
          - "date && echo 'presync'"
      restartPolicy: Never
  backoffLimit: 2
