kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: custom-s2i
spec:
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "ruby:2.5"
        namespace: "openshift"
      env:
        - name: MYVAL
          value: “test”
  source:
    git:
      uri: "https://github.com/mosuke5/ruby-hello-world.git"
      ref: "master"
  output:
    to:
      kind: ImageStreamTag
      name: 'custom-s2i:unset-myval'
      #name: 'custom-s2i:latest'
---
kind: ImageStream
apiVersion: v1
metadata:
  name: custom-s2i
