apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-a
  name: nginx-a
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-a
  template:
    metadata:
      labels:
        app: nginx-a
    spec:
      containers:
        - image: nginx-a:latest
          name: nginx-a
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            failureThreshold: 30
            periodSeconds: 30
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-a
spec:
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  selector:
    app: nginx-a
