resources:
  - ../base
images:
  - name: nginx-a
    newName: nginxinc/nginx-unprivileged
    newTag: "prod-1.19"
  - name: nginx-b
    newName: nginxinc/nginx-unprivileged
    newTag: "prod-1.20"
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: image-pull-secret }]
